let invoiceRecords=[],invoiceLineRecords=[],editingInvoice=null,editingLines=[];
const invMoney=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const invEsc=v=>String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const statusText=s=>s==="sent"?"Sent":s==="paid"?"Paid":s==="void"?"Void":"Draft";
function updateInvoiceBadge(s){const b=document.getElementById("invoiceBadge");if(b){b.className=`invoice-status-badge ${s||"draft"}`;b.textContent=statusText(s)}}
async function loadInvoices(){if(!client)return;const[a,b]=await Promise.all([client.from("invoices").select("*").order("created_at",{ascending:false}),client.from("invoice_items").select("*").order("sort_order",{ascending:true})]);if(a.error){document.getElementById("adminInvoices").innerHTML=`<p class="muted">${invEsc(a.error.message)}</p>`;return}invoiceRecords=a.data||[];invoiceLineRecords=b.error?[]:(b.data||[]);renderInvoices()}
function renderInvoices(){const box=document.getElementById("adminInvoices");if(!box)return;const q=(document.getElementById("invoiceSearch")?.value||"").toLowerCase(),f=document.getElementById("invoiceFilter")?.value||"all";const rows=invoiceRecords.filter(x=>`${x.invoice_number} ${x.customer_name} ${x.customer_email} ${x.customer_company||""}`.toLowerCase().includes(q)&&(f==="all"||x.status===f));box.innerHTML=rows.length?rows.map(x=>`<article class="invoice-admin-card"><div class="invoice-admin-head"><div><h3>${invEsc(x.invoice_number)}</h3><div class="muted">${new Date(x.created_at).toLocaleDateString()}</div></div><span class="invoice-status-badge ${invEsc(x.status)}">${statusText(x.status)}</span></div><div class="invoice-admin-meta"><div><span>Customer</span><strong>${invEsc(x.customer_name)}</strong></div><div><span>Email</span><a href="mailto:${invEsc(x.customer_email)}">${invEsc(x.customer_email)}</a></div><div><span>Total</span><strong>${invMoney(x.total)}</strong></div><div><span>Due</span><strong>${invEsc(x.due_date||"Not set")}</strong></div></div><div class="actions"><button class="btn blue" onclick="openInvoice('${x.id}')">Open</button><button class="btn pink" onclick="emailInvoiceById('${x.id}')">Email</button><button class="btn green" onclick="markInvoice('${x.id}','paid')">Mark Paid</button><button class="btn" onclick="printInvoiceById('${x.id}')">Print</button><button class="btn danger" onclick="deleteInvoice('${x.id}')">Delete</button></div></article>`).join(""):'<p class="muted">No matching invoices.</p>'}
function createInvoiceFromOrder(id){const o=orderRequests.find(x=>String(x.id)===String(id));if(!o){alert("Order request not found.");return}const items=orderRequestItems.filter(x=>String(x.order_request_id)===String(id)),due=new Date();due.setDate(due.getDate()+7);editingInvoice={id:null,order_request_id:o.id,invoice_number:"Assigned when saved",customer_name:o.name||"",customer_email:o.email||"",customer_phone:o.phone||"",customer_company:o.company||"",status:"draft",due_date:due.toISOString().slice(0,10),discount:0,shipping:0,tax_rate:0,tax_amount:0,subtotal:0,total:0,notes:"",internal_notes:o.notes||""};editingLines=(items.length?items:[{product_name:"Research Material",strength:"",quantity:1}]).map((x,i)=>({description:x.product_name||"Research Material",option_text:x.strength||"",quantity:Number(x.quantity||1),unit_price:0,line_total:0,sort_order:i}));fillInvoice()}
function openInvoice(id){const x=invoiceRecords.find(v=>String(v.id)===String(id));if(!x)return;editingInvoice={...x};editingLines=invoiceLineRecords.filter(v=>String(v.invoice_id)===String(id)).map(v=>({...v}));fillInvoice()}
function fillInvoice(){document.getElementById("invoiceTitle").textContent=editingInvoice.id?"Edit Invoice":"Create Invoice";for(const [id,key] of [["invNumber","invoice_number"],["invName","customer_name"],["invEmail","customer_email"],["invPhone","customer_phone"],["invCompany","customer_company"],["invDue","due_date"],["invStatus","status"],["invDiscount","discount"],["invShipping","shipping"],["invTaxRate","tax_rate"],["invNotes","notes"],["invInternal","internal_notes"]])document.getElementById(id).value=editingInvoice[key]||"";updateInvoiceBadge(editingInvoice.status);renderInvoiceLines();recalculateInvoice();document.getElementById("invoiceMessage").textContent="";document.getElementById("invoiceModal").classList.add("open")}
function closeInvoiceEditor(){document.getElementById("invoiceModal").classList.remove("open")}
function renderInvoiceLines(){document.getElementById("invoiceLines").innerHTML=editingLines.map((x,i)=>`<div class="invoice-line"><input value="${invEsc(x.description)}" oninput="changeLine(${i},'description',this.value)"><input value="${invEsc(x.option_text||"")}" oninput="changeLine(${i},'option_text',this.value)"><input type="number" min="1" value="${Number(x.quantity||1)}" oninput="changeLine(${i},'quantity',this.value)"><input type="number" min="0" step="0.01" value="${Number(x.unit_price||0)}" oninput="changeLine(${i},'unit_price',this.value)"><strong>${invMoney(x.line_total)}</strong><button class="btn danger compact" onclick="removeInvoiceLine(${i})">×</button></div>`).join("")}
function changeLine(i,k,v){const x=editingLines[i];x[k]=(k==="quantity"||k==="unit_price")?Number(v||0):v;x.quantity=Math.max(1,Number(x.quantity||1));x.unit_price=Math.max(0,Number(x.unit_price||0));x.line_total=x.quantity*x.unit_price;recalculateInvoice();renderInvoiceLines()}
function addInvoiceLine(){editingLines.push({description:"",option_text:"",quantity:1,unit_price:0,line_total:0,sort_order:editingLines.length});renderInvoiceLines()}
function removeInvoiceLine(i){editingLines.splice(i,1);renderInvoiceLines();recalculateInvoice()}
function recalculateInvoice(){if(!editingInvoice)return;editingLines.forEach(x=>x.line_total=Number(x.quantity||0)*Number(x.unit_price||0));const s=editingLines.reduce((a,x)=>a+Number(x.line_total||0),0),d=Math.max(0,Number(document.getElementById("invDiscount")?.value||0)),sh=Math.max(0,Number(document.getElementById("invShipping")?.value||0)),r=Math.max(0,Number(document.getElementById("invTaxRate")?.value||0)),tax=Math.max(0,s-d+sh)*r/100,t=Math.max(0,s-d+sh)+tax;Object.assign(editingInvoice,{subtotal:s,discount:d,shipping:sh,tax_rate:r,tax_amount:tax,total:t});document.getElementById("invSubtotal").textContent=invMoney(s);document.getElementById("invTax").textContent=invMoney(tax);document.getElementById("invTotal").textContent=invMoney(t)}
function collectInvoice(){Object.assign(editingInvoice,{customer_name:document.getElementById("invName").value.trim(),customer_email:document.getElementById("invEmail").value.trim(),customer_phone:document.getElementById("invPhone").value.trim(),customer_company:document.getElementById("invCompany").value.trim(),due_date:document.getElementById("invDue").value||null,status:document.getElementById("invStatus").value,notes:document.getElementById("invNotes").value.trim(),internal_notes:document.getElementById("invInternal").value.trim()});recalculateInvoice()}
async function saveInvoice(){collectInvoice();if(!editingInvoice.customer_name||!editingInvoice.customer_email){alert("Customer name and email are required.");return}const payload={...editingInvoice};delete payload.id;delete payload.invoice_number;delete payload.created_at;let r=editingInvoice.id?await client.from("invoices").update(payload).eq("id",editingInvoice.id).select("*").single():await client.from("invoices").insert(payload).select("*").single();if(r.error){alert(r.error.message);return}editingInvoice={...r.data};await client.from("invoice_items").delete().eq("invoice_id",editingInvoice.id);const ir=await client.from("invoice_items").insert(editingLines.map((x,i)=>({invoice_id:editingInvoice.id,description:x.description||"Item",option_text:x.option_text||null,quantity:Number(x.quantity||1),unit_price:Number(x.unit_price||0),line_total:Number(x.line_total||0),sort_order:i}))).select("*");if(ir.error){alert(ir.error.message);return}editingLines=ir.data||[];document.getElementById("invNumber").value=editingInvoice.invoice_number;document.getElementById("invoiceMessage").textContent="Invoice saved.";await loadInvoices()}
async function emailInvoice(){if(!editingInvoice?.id)await saveInvoice();if(!editingInvoice?.id)return;const r=await fetch("/.netlify/functions/send-invoice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invoice_id:editingInvoice.id})}),j=await r.json().catch(()=>({}));if(!r.ok){alert(j.error||"Invoice could not be emailed.");return}await client.from("invoices").update({status:"sent",sent_at:new Date().toISOString()}).eq("id",editingInvoice.id);editingInvoice.status="sent";updateInvoiceBadge("sent");document.getElementById("invoiceMessage").textContent="Invoice emailed.";await loadInvoices()}
async function emailInvoiceById(id){openInvoice(id);await emailInvoice()}
async function markInvoice(id,status){const u={status,updated_at:new Date().toISOString()};if(status==="paid")u.paid_at=new Date().toISOString();const r=await client.from("invoices").update(u).eq("id",id);if(r.error)alert(r.error.message);else await loadInvoices()}
async function deleteInvoice(id){if(!confirm("Delete this invoice?"))return;const r=await client.from("invoices").delete().eq("id",id);if(r.error)alert(r.error.message);else await loadInvoices()}
function printMarkup(inv,lines){const rows=lines.map(x=>`<tr><td>${invEsc(x.description)}</td><td>${invEsc(x.option_text||"")}</td><td>${x.quantity}</td><td>${invMoney(x.unit_price)}</td><td>${invMoney(x.line_total)}</td></tr>`).join("");return `<!doctype html><html><head><style>body{font-family:Arial;padding:40px}table{width:100%;border-collapse:collapse;margin:30px 0}th,td{padding:12px;border-bottom:1px solid #ddd}.tot{width:320px;margin-left:auto}</style></head><body><h2>Neon Peppers</h2><h1>Invoice ${invEsc(inv.invoice_number)}</h1><p><b>Bill To:</b><br>${invEsc(inv.customer_name)}<br>${invEsc(inv.customer_email)}</p><table><tr><th>Description</th><th>Option</th><th>Qty</th><th>Price</th><th>Total</th></tr>${rows}</table><div class="tot"><p>Subtotal: ${invMoney(inv.subtotal)}</p><p>Discount: -${invMoney(inv.discount)}</p><p>Shipping: ${invMoney(inv.shipping)}</p><p>Tax: ${invMoney(inv.tax_amount)}</p><h2>Total: ${invMoney(inv.total)}</h2></div></body></html>`}
function printInvoice(){collectInvoice();const w=window.open("","_blank");w.document.write(printMarkup(editingInvoice,editingLines));w.document.close();setTimeout(()=>w.print(),200)}
function printInvoiceById(id){const inv=invoiceRecords.find(x=>String(x.id)===String(id));if(!inv)return;const lines=invoiceLineRecords.filter(x=>String(x.invoice_id)===String(id)),w=window.open("","_blank");w.document.write(printMarkup(inv,lines));w.document.close();setTimeout(()=>w.print(),200)}
