const VERIFY_KEY="neonPeppersResearchVerified";
const demoProducts=[
 {id:"demo1",name:"BPC-157 + TB-500",category:"Research Compound",description:"Reference information for controlled laboratory and analytical research.",strength:"10 MG",image_url:"",coa_url:"",visible:true},
 {id:"demo2",name:"Tesamorelin",category:"Research Compound",description:"Reference material presented solely for qualified laboratory research.",strength:"10 MG",image_url:"",coa_url:"",visible:true},
 {id:"demo3",name:"KPV",category:"Research Compound",description:"Short peptide reference material for laboratory and analytical applications.",strength:"10 MG",image_url:"",coa_url:"",visible:true}
];
let allProducts=[];
function esc(v){return String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function initGate(){const gate=document.getElementById("researchGate");if(!gate)return;if(sessionStorage.getItem(VERIFY_KEY)!=="yes"){document.body.classList.add("gated");gate.classList.add("open")}const boxes=[...gate.querySelectorAll('input[type="checkbox"]')],enter=document.getElementById("enterSite");const update=()=>enter.disabled=!boxes.every(x=>x.checked);boxes.forEach(x=>x.addEventListener("change",update));enter.addEventListener("click",()=>{sessionStorage.setItem(VERIFY_KEY,"yes");gate.classList.remove("open");document.body.classList.remove("gated")})}
function getClient(){const c=window.NEON_CONFIG||{};return c.supabaseUrl&&c.supabasePublishableKey&&window.supabase?window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey):null}
async function loadProducts(){const client=getClient();if(!client){allProducts=demoProducts;renderFilters();renderProducts();return}try{const {data,error}=await client.from("products").select("*").eq("visible",true).order("created_at",{ascending:false});if(error)throw error;allProducts=data?.length?data:demoProducts}catch(e){console.warn(e);allProducts=demoProducts}renderFilters();renderProducts()}
function renderFilters(){const f=document.getElementById("filters");if(!f)return;const cats=["All",...new Set(allProducts.map(p=>p.category||"Research Compound"))];f.innerHTML=cats.map((c,i)=>`<button class="filter ${i===0?"active":""}" data-cat="${esc(c)}">${esc(c)}</button>`).join("");f.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{f.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProducts()})}
function renderProducts(){const grid=document.getElementById("productGrid");if(!grid)return;const q=(document.getElementById("searchInput")?.value||"").toLowerCase(),cat=document.querySelector(".filter.active")?.dataset.cat||"All";const list=allProducts.filter(p=>(cat==="All"||p.category===cat)&&(`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q)));if(!list.length){grid.innerHTML='<div class="empty">No matching research materials found.</div>';return}grid.innerHTML="";list.forEach(p=>{const card=document.createElement("article");card.className="card";card.onclick=()=>openProduct(p);const img=p.image_url?`style="background-image:url('${String(p.image_url).replace(/'/g,"%27")}')"`:"";card.innerHTML=`<div class="card-image" ${img}>${p.image_url?"":"⚗"}</div><div class="card-body"><div class="category">${esc(p.category||"Research Compound")}</div><h3>${esc(p.name)}</h3><p>${esc(p.description||"Laboratory research reference material.")}</p><div class="strength">${esc(p.strength||"")}</div></div>`;grid.appendChild(card)})}
function openProduct(p){const m=document.getElementById("productModal"),img=document.getElementById("modalImage");img.style.backgroundImage=p.image_url?`url("${p.image_url}")`:"";img.textContent=p.image_url?"":"⚗";document.getElementById("modalCategory").textContent=p.category||"Research Compound";document.getElementById("modalName").textContent=p.name;document.getElementById("modalDescription").textContent=p.description||"";document.getElementById("modalStrength").textContent=p.strength||"Not listed";const coa=document.getElementById("modalCoa");if(p.coa_url){coa.href=p.coa_url;coa.style.display="inline-flex"}else coa.style.display="none";m.classList.add("open")}
function closeProduct(){document.getElementById("productModal")?.classList.remove("open")}
document.addEventListener("DOMContentLoaded",()=>{initGate();loadProducts();document.getElementById("searchInput")?.addEventListener("input",renderProducts);document.getElementById("menuBtn")?.addEventListener("click",()=>document.getElementById("navLinks")?.classList.toggle("open"));document.getElementById("productModal")?.addEventListener("click",e=>{if(e.target.id==="productModal")closeProduct()})});
