alter table public.products add column if not exists featured boolean default false, add column if not exists updated_at timestamptz default now();
alter table public.products enable row level security;
drop policy if exists "Public can view visible products" on public.products;
create policy "Public can view visible products" on public.products for select using (visible = true);
drop policy if exists "Authenticated users can manage products" on public.products;
create policy "Authenticated users can manage products" on public.products for all to authenticated using (true) with check (true);
insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict (id) do update set public=true;
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images" on storage.objects for select using (bucket_id='product-images');
drop policy if exists "Authenticated users upload product images" on storage.objects;
create policy "Authenticated users upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images');
drop policy if exists "Authenticated users update product images" on storage.objects;
create policy "Authenticated users update product images" on storage.objects for update to authenticated using (bucket_id='product-images') with check (bucket_id='product-images');
drop policy if exists "Authenticated users delete product images" on storage.objects;
create policy "Authenticated users delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images');
